# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:testClient1 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.66', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "ts-net"},
            ]
},
:testClient2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.67', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "ts-net"},
            ]
  },
:testServer1 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.68', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "ts-net"},
            ]
},
:testServer2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.69', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "ts-net"},
            ]
  },
:inetRouter => {
    :box_name => "centos/6",
    #:public => {:ip => '10.10.10.1', :adapter => 1},
    :net => [
               {adapter: 2, virtualbox__intnet: "router-net"},
               {adapter: 3, virtualbox__intnet: "router-net"},
            ]
  },
:centralRouter => {
    :box_name => "centos/7",
    :net => [
               {adapter: 2, virtualbox__intnet: "router-net"},
               {adapter: 6, virtualbox__intnet: "router-net"},
               {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
               {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
               {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
            ]
  },
:office1Router => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.1', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dir-net"},
               {ip: '192.168.2.65', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "ts-net"},
               {ip: '192.168.2.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "manager-net"},
               {ip: '192.168.2.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
            ]
  }, 
:office2Router => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.1.1', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dir-net"},
              {ip: '192.168.1.129', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "ts-net"},
              {ip: '192.168.1.193', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "manager-net"},
            ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "testClient1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
          echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1
          echo "ONBOOT=yes\nTYPE=VLAN\nVLAN=yes\nVLAN_NAME_TYPE=VLAN_PLUS_VID_NO_PAD\nDEVICE=vlan2\nPHYSDEV=eth1\nVLAN_ID=2\nBOOTPROTO=static\nIPADDR=10.10.10.254\nNETMASK=255.255.255.0" >> /etc/sysconfig/network-scripts/ifcfg-vlan2
          cp /vagrant/ssh/server1 /home/vagrant/.ssh/id_rsa
          chown vagrant:vagrant /home/vagrant/.ssh/id_rsa
          cat /vagrant/ssh/server1.pub >> /home/vagrant/.ssh/authorized_keys
          sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          service sshd restart
          systemctl restart network
          SHELL
        when "testClient2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
          echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1
          nmcli connection add type vlan ifname vlan3 dev eth1 id 3 ip4 10.10.10.1/24
          cp /vagrant/ssh/server2 /home/vagrant/.ssh/id_rsa
          chown vagrant:vagrant /home/vagrant/.ssh/id_rsa
          cat /vagrant/ssh/server2.pub >> /home/vagrant/.ssh/authorized_keys
          sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          service sshd restart
          systemctl restart network
          SHELL
        when "testServer1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
          echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1
          echo "ONBOOT=yes\nTYPE=VLAN\nVLAN=yes\nVLAN_NAME_TYPE=VLAN_PLUS_VID_NO_PAD\nDEVICE=vlan2\nPHYSDEV=eth1\nVLAN_ID=2\nBOOTPROTO=static\nIPADDR=10.10.10.1\nNETMASK=255.255.255.0" >> /etc/sysconfig/network-scripts/ifcfg-vlan2
          cp /vagrant/ssh/server1 /home/vagrant/.ssh/id_rsa
          chown vagrant:vagrant /home/vagrant/.ssh/id_rsa
          cat /vagrant/ssh/server1.pub >> /home/vagrant/.ssh/authorized_keys
          sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          service sshd restart
          systemctl restart network
          SHELL
        when "testServer2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
          echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1
          nmcli connection add type vlan ifname vlan3 dev eth1 id 3 ip4 10.10.10.254/24
          cp /vagrant/ssh/server2 /home/vagrant/.ssh/
          chown vagrant:vagrant /home/vagrant/.ssh/id_rsa
          cat /vagrant/ssh/server2.pub >> /home/vagrant/.ssh/authorized_keys
          sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          service sshd restart
          systemctl restart network
          SHELL
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
            touch /etc/sysconfig/network-scripts/route-bond0
            touch /etc/sysconfig/network-scripts/ifcfg-bond0            
            echo "192.168.0.0/24 via 192.168.255.2 dev bond0" >> /etc/sysconfig/network-scripts/route-bond0
            echo "192.168.1.0/24 via 192.168.255.2 dev bond0" >> /etc/sysconfig/network-scripts/route-bond0
            echo "192.168.2.0/24 via 192.168.255.2 dev bond0" >> /etc/sysconfig/network-scripts/route-bond0
            echo "DEVICE=bond0\nNAME=bond0\nTYPE=Bond\nBONDING_MASTER=YES\nIPADDR=192.168.255.1\nPREFIX=30\nONBOOT=yes\nBOOTPROTO=none\nBONDING_OPTS="mode=1 miimon=100 primary=eth1"" >> /etc/sysconfig/network-scripts/ifcfg-bond0 
            echo "TYPE=Ethernet\nBOOTPROTO=none\nONBOOT=yes\nDEVICE=eth1\nMASTER=bond0\nSLAVE=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "TYPE=Ethernet\nBOOTPROTO=none\nONBOOT=yes\nDEVICE=eth2\nMASTER=bond0\nSLAVE=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth2
            service network restart
            SHELL
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
            echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            nmcli connection modify "System eth2" +ipv4.addresses 192.168.11.1/30
            nmcli connection modify "System eth2" +ipv4.addresses 192.168.12.1/30
            touch /etc/sysconfig/network-scripts/route-eth2
            nmcli connection add type bond ifname bon0 con-name bond0 mode active-backup primary eth1 miimon 100 ip4 192.168.255.2 gw4 192.168.255.1
            nmcli connection add type bond-slave ifname eth1 master bond0
            nmcli connection add type bond-slave ifname eth5 master bond0
            echo "192.168.2.0/24 via 192.168.12.2" >> /etc/sysconfig/network-scripts/route-eth2
            echo "192.168.1.0/24 via 192.168.11.2" >> /etc/sysconfig/network-scripts/route-eth2
            systemctl restart network
            sysctl -p
            SHELL
        when "office1Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          nmcli connection modify "System eth1" +ipv4.gateway 192.168.12.1
          nmcli connection modify "System eth1" +ipv4.addresses 192.168.12.2/30
          systemctl restart network
          sysctl -p
          SHELL
        when "office2Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          nmcli connection modify "System eth1" +ipv4.gateway 192.168.11.1
          nmcli connection modify "System eth1" +ipv4.addresses 192.168.11.2/30
          systemctl restart network
          sysctl -p
          SHELL
        end 

      end

  end
  
  
end