---
# tasks file for server-rsyslog-conf

- name: Install epel release
  yum:
    name: epel-release

- name: install nginx
  yum:
    name: nginx


- name: add configure nginx 
  template: 
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf 


- name: start nginx web server
  systemd:
    state: started
    name: nginx
    enabled: yes