# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:group1Client1 => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.140.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ts-net"},
            ]
},
:group1Client2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.140.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ts-net"},
            ]
  },
:group2Cleint1 => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.150.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ts-net"},
            ]
},
:grpoup2Client2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.150.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ts-net"},
            ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "grpoup1Client1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          SHELL
        when "grpoup1Client2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          SHELL
        when "grpoup2Client1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          SHELL
        when "grpoup2Client2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          SHELL
        end 

      end

  end
  
  
end