---
# handlers file for dns-server
- name: restart bind
  systemd:
    name: named
    state: reloaded
    enabled: yes

- name: start bind service
  systemd:
    name: named
    enabled: yes
    state: started