---
- name: install bind server
  yum: 
    name: '{{ packages_list }}'
    state: present

- name: Copy Default config dns server
  template: 
    src: named.conf.j2
    dest: /etc/named.conf
  notify: start bind service

- name: add otushw.ru zone dns server
  template: 
    src: db.otushw.ru.j2
    dest: "/etc/named/db.otushw.ru"
  vars: 
    all_servers: "{{ groups['all'] }}"
  notify: 
    - restart bind

- name: add rev otushw.ru zone dns server
  template: 
    src: db.rev_otushw.ru.j2
    dest: "/etc/named/db.rev_otushw.ru"
  vars: 
    all_servers: "{{ groups['all'] }}"
  notify: 
    - restart bind