# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:vpnServer => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.140.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "openvpn-net"},
            ]
    },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
            box.vm.network "private_network", ipconf
            box.vm.network "public_network"
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "vpnServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            yum install -y epel-release && yum install -y openvpn
            mkdir /etc/openvpn/server/ssl
            mkdir /var/log/openvpn
        SHELL

        end 

      end

  end
  
  
end