---
- name: Add ignore table for slave server
  become: true
  blockinfile: 
    dest: /etc/my.cnf.d/05-binlog.cnf
    block: |
        replicate-ignore-table=bet.events_on_demand
        replicate-ignore-table=bet.v_same_event

- name: Configure replication on the slave
  become: false
  mysql_replication: 
    mode: changemaster
    master_host: '192.168.11.150'
    master_user: 'repl'
    master_password: '!OtusLinux2018'
    master_auto_position: '1'


- name: Restart service mysql for slave server
  become: true
  systemd: 
    name: mysql
    state: restarted