# -*- mode: ruby -*-
# vim: set ft=ruby :


MACHINES = {
:Client1 => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.140.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ts-net"},
            ]
},
:Client2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.140.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ts-net"},
            ]
  },
:Client3 => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.140.3', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ts-net"},
            ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "Client1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          SHELL

        
        when "Client2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          SHELL
    

        when "Client3"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          SHELL
        end 

      end

  end
  
  
end