# -*- mode: ruby -*-
# vi: set ft=ruby :


MACHINES = {
    log: {
        :box_name => 'centos/7',
        :ip_addr => '192.168.11.10',
        :memory => 1024,
        :cpu => 2
    },

    web: {
        :box_name => 'centos/7',
        :ip_addr => '192.168.11.20',
        :memory => '512',
        :cpu => 1
    }
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", boxconfig[:memory]]
                vb.customize ["modifyvm", :id, "--cpus", boxconfig[:cpu]]
            end
            box.vm.network "private_network", ip: boxconfig[:ip_addr]

            
            box.vm.provision "shell", inline: <<-SHELL
              mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
              sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
              systemctl restart sshd
              setenforce 0
            SHELL
        end
    end
  end
  #  config.vm.provision "ansible" do |ansible|
  #    ansible.inventory_path = "staging/hosts"
  #    ansible.playbook = "main.yml"
  #    ansible.limit = "all"
  #  end  