---
# tasks file for percona-server
- name: add percona repository
  yum: 
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: install percona server
  yum:
    name: [ 'Percona-Server-server-57', 'MySQL-python.x86_64' ]
    state: present

- name: Copy base configuration percona server
  template: 
    src: '{{ item }}'
    dest: /etc/my.cnf.d/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob: 
    - 'templates/0*.j2'
  notify: 
    - Add table slave server 

- name: Copy base configuration authorization for mysql vagrant user
  template: 
    src: templates/my.cnf.j2
    dest: /home/vagrant/.my.cnf

- name: start percona server for master-host
  systemd: 
    state: started
    name: mysql
    enabled: yes
  notify: 
    - Read default pass for root user mysql
    - update mysql root password
