---
# tasks file for percona-server
- name: add percona repository
  yum: 
    name: "{{ percona_repo }}"
    state: present

- name: install percona server and other necessary packages
  yum:
    name: "{{ server_packages }}"
    state: present

- name: Copy base configuration percona server
  template: 
    src: '{{ item }}'
    dest: /etc/my.cnf.d/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob: 
    - 'templates/0*.j2'

- name: Copy base configuration authorization for mysql vagrant user
  template: 
    src: templates/my.cnf.j2
    dest: /home/vagrant/.my.cnf

- name: start percona server
  systemd: 
    state: started
    name: mysql
    enabled: yes
  notify: 
    - Read default pass for root user mysql
    - update mysql root password
