---
- hosts: inetRouter
  become: yes
  tasks:
    - name: install libselinux-python, him need configured sysctl and all system config. 
      yum:
        name: libselinux-python
        state: latest
  
  
  
    - name: Enable ip forwarding all interface
      sysctl: 
        name: net.ipv4.conf.all.forwarding
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: configure static route inetRoute -> centralServer
      shell: echo "192.168.0.0/24 via 192.168.255.2 dev eth1" >> /etc/sysconfig/network-scripts/route-eth1
    
    - name: restore iptables
      shell: iptables-restore /vagrant/iptables/inetRouter

    - name: update sshd config and enable PasswordAuthentication
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication.*no'
        line: 'PasswordAuthentication=yes'
      notify: restart_sshd

  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted


- hosts: inetRouter2
  become: yes
  tasks:
    - name: Enable ip forwarding all interface
      sysctl: 
        name: net.ipv4.conf.all.forwarding
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: dnat 80 port eth2 to 192.168.255.2:80
      iptables: 
        table: nat
        chain: PREROUTING
        in_interface: eth2
        protocol: tcp
        destination_port: 80
        jump: DNAT
        to_destination: 192.168.255.2
        
    - name: snat source ip in connection to inetRoute2 for publicip and 80 port
      iptables: 
        table: nat
        chain: POSTROUTING
        protocol: tcp
        destination: 192.168.255.2
        destination_port: 80
        jump: SNAT
        to_source: 192.168.255.3