#!/bin/bash
dayWeek=`date +%u`

if [[ grep $PAM_USER /etc/group | grep 'admin' ]]
then
        exit 0
fi
if [[ $dayWeek > 5 ]]
then
        exit 1
elif [[ cat /vagrant/holidays2018 | grep `date "+%d/%m"` ]]
then
        exit 1
else
        exit 0
fi