#!/bin/bash
dayWeek=`date +%u`
daydm=`date +%d/%m`

#if [[ `grep $PAM_USER /etc/group | grep admin` ]]
#then
#        exit 0
#fi

if [[ $dayWeek > 5 ]]
then
        exit 1
fi

if [[ `grep $daydm /vagrant/holidays2018` ]]
then
        echo "true $?"
        exit 0
else
        echo "false $?"
        exit 0
fi