# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:aaaServer => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.140.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "openvpn-net"},
            ]
    },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
            box.vm.network "private_network", ipconf
            box.vm.network "public_network"
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
          sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          yum install epel-release -y
          yum install pam_scripts -y
          useradd jhonsnow -p 123456
          useradd ariastark -p 123456
          groupadd admin
          usermod jhonsnow -G admin
          cp /vagrant/pam-script /etc/
          chmod +x /etc/pam-script
          echo "auth   required   pam_script.so" >> /etc/pam.d/sshd
          SHELL
        end 

      end
    
    end