# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "otusClient"
    config.vm.synced_folder ".", "/vagrant"
    ansible_inventory_dir = "staging/hosts"
  


    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end

    config.vm.provision "shell", inline: <<-SHELL
              mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
              sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
              systemctl restart sshd    
    SHELL

    config.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "staging/hosts"
      ansible.playbook = "main.yml"
      ansible.limit = "all"
    end

  end

  