---

- name: Create sysctl configuration
  template:
    src: sysctl.conf.j2
    dest: "{{ sysctl_config_location }}"
  notify:
    - Reload sysctl configuration
  tags:
    - sysctl_config
  
- name: Add or modify nofile soft limit for all user
  pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: 100000
  
- name: Add or modify nofile soft limit for all user
  pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: 100000