# -*- mode: ruby -*-
# vi: set ft=ruby :


MACHINES = {
    ipaserver: {
        :box_name => 'centos/7',
        :ip_addr => '192.168.11.10',
        :memory => '2048'
    },

    ipaclient: {
        :box_name => 'centos/7',
        :ip_addr => '192.168.11.20',
        :memory => '512'
    }
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", "2048"]
            end

        
            
            box.vm.provision "shell", inline: <<-SHELL
              mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
              sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
              systemctl restart sshd
              setenforce 0
            SHELL

            box.vm.provision "ansible" do |ansible|
                ansible.playbook = "main.yml"
            end
        end
    end
  end