---
# handlers file for percona-server
- name: Add table slave server 
  blockinfile: 
    path: /etc/my.cnf.d/05-binlog.cnf
    block: |
        replicate-ignore-table=bet.events_on_demand
        replicate-ignore-table=bet.v_same_event
  when: serverid != 1  

