# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "otuslinux"
    config.vm.network "public_network", :mac => "080027ff13ac"
    config.vm.synced_folder ".", "/vagrant"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    config.vm.provision "shell", inline: <<-SHELL
    yum -y install epel-release
    yum -y install httpd spawn-fcgi mod_fcgid  php php-cli
    cp /vagrant/conf/greplog.service /etc/systemd/system/greplog.service
    cp /vagrant/conf/greplog.timer /etc/systemd/system/greplog.timer
    cp /vagrant/conf/spawn-fcgi.service /etc/systemd/system/spawn-fcgi.service
    cp /vagrant/conf/greplog.sh /home/vagrant/greplog.sh
    cp /vagrant/conf/greplog /etc/sysconfig/greplog
    echo "y" | cp /vagrant/conf/spawn-fcgi /etc/sysconfig/spawn-fcgi
    cp /vagrant/conf/httpd@.service /etc/systemd/system/
    cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/test1.conf
    sed -i '32iPidFile "/var/run/httpd@test1.pid"' /etc/httpd/conf/test1.conf
    sed -i  's/Listen 80/Listen 8080/' /etc/httpd/conf/test1.conf
    systemctl start greplog.service
    systemctl start greplog.timer    
    systemctl enable greplog.service
    systemctl enable greplog.timer
    systemctl start spawn-fcgi.service
    systemctl enable spawn-fcgi.service
    systemctl start httpd
    systemctl enable httpd
    
    SHELL

  end

  