# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:vpnServer => {
    :box_name => "centos/7",
    :net => [
               {ip: '10.10.140.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "openvpn-net"},
            ]
    },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
            box.vm.network "private_network", ipconf
            box.vm.network "public_network"
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
          mkdir  /etc/openvpn
          mkdir  /etc/samba
                cp /vagrant/server.conf /etc/openvpn/server.conf
          echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
          echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
          sysctl -p /etc/sysctl.conf
          
          systemctl restart network
        SHELL
        
        case boxname.to_s
        when "vpnServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            yum install -y epel-release && yum install -y openvpn
            mkdir /etc/openvpn/server/ssl
            mkdir /etc/openvpn/ccd
            ###  Генируем сертификат СА
            openssl genrsa -out /etc/openvpn/server/ssl/ca.key 2048
            openssl req -x509 -new -key /etc/openvpn/server/ssl/ca.key -days 3650 -out /etc/openvpn/server/ssl/ca.crt -subj '/C=RU/CN=CAserver/O=Otus'
            ### Генерируем Сертификат OpenVpnServer, который подписываем корневым
            openssl genrsa -out /etc/openvpn/server/ssl/server.key 2048
            openssl req -new -key /etc/openvpn/server/ssl/server.key -days 365 -out /etc/openvpn/server/ssl/server.crt -subj '/C=RU/CN=VpnServer/O=Otus'
            openssl x509 -req -days 365 -in /etc/openvpn/server/ssl/server.crt -CA /etc/openvpn/server/ssl/ca.crt -CAkey /etc/openvpn/server/ssl/ca.key -set_serial 01 -out /etc/openvpn/server/ssl/server.crt
            ###  Генерируем ключ DH
            openssl dhparam -out /etc/openvpn/server/ssl/VpnDH1024.pem 1024
            ###  Создаем ключ для клиента
            mkdir -p /var/share/VpnClient
            openssl genrsa -out /var/share/VpnClient/client1.key 2048
            openssl req -new -key /var/share/VpnClient/client1.key -days 3650 -out /var/share/VpnClient/client1.crt -subj '/C=RU/O=Otus/CN=userVpn1'
            openssl x509 -req -days 3650 -in /var/share/VpnClient/client1.crt -CA /etc/openvpn/server/ssl/ca.crt -CAkey /etc/openvpn/server/ssl/ca.key -set_serial 01 -out /var/share/VpnClient/client1.crt
            cp /etc/openvpn/server/ssl/ca.crt /var/share/VpnClient/ca.crt
            ### Создадим папку для логов
            mkdir /var/log/openvpn
            ###  Установка samba для шары с конфигом клиента OpenVPN
            yum install -y samba
            cp -f /vagrant/smb.conf /etc/samba/smb.conf
            setenforce 0
            systemctl start openvpn@server
            systemctl start smb
        SHELL

        end 

      end

  end
  
  
end