---
# tasks file for master-mysql
- name: create database "bet"
  mysql_db:
    login_user: root
    login_password: "{{ rootmysql }}"
    name: bet
    state: present

- name: Load dump bet.dmp to database "bet"
  mysql_db: 
    login_user: root
    login_password: "{{ rootmysql }}"
    name: bet
    state: import
    target: /vagrant/bet.dmp

- name: create dump for slave server
  mysql_db:
    login_user: root
    login_password: "{{ rootmysql }}"
    state: dump
    name: all
    ignore_tables: "{{ item }}"
    target: /home/vagrant/slave_bet.sql
  with_items: 
    - bet.events_on_demand
    - bet.v_same_event
