---
# tasks file for master-mysql
- name: create database "bet"
  mysql_db:
    name: bet
    state: present
  notify: 
    - Load dump bet.dmp to database "bet"
    - create dump for slave server


- name: copy dump database to slave server
  fetch: 
    src: /home/vagrant/bet_for_slave.sql
    dest: /tmp/fetched