# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 250, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 250,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 250, # Megabytes
                        :port => 4
                },
		:sata5 => {
			:dfile => './sata5.vdi',
			:size => 250,
			:port => 5 
		},
		:sata6 => {
                        :dfile => './sata6.vdi',
                        :size => 250, # Megabytes
                        :port => 6
                },
                :sata7 => {
                        :dfile => './sata7.vdi',
                        :size => 250,
                        :port => 7
                },
                :sata8 => {
                        :dfile => './sata8.vdi',
                        :size => 250, # Megabytes
                        :port => 8
                }

	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
		  vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]

		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
			  end
			  vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]

		  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
	      mdadm --create /dev/md0 --level 6 n 4 /dev/sd{b,c,d,e}
	      mdadm --create /dev/md0 --level 6 -n 4 /dev/sd{b,c,d,e}
	      mdadm --create /dev/md1 --level 6 -n 4 /dev/sd{f,g,h,i}
	      mdadm --create /dev/md2 --level 0 -n 2 /dev/md{0,1}
  	      parted /dev/md2 mklabel gpt mkpart P1 ext3 1MiB 100MiB 
	      parted /dev/md2 mkpart P2 ext4 100MiB 120MiB 
	      parted /dev/md2 mkpart P3 ext4 120MiB 500MiB 
	      parted /dev/md2 mkpart P4 ext4 500MiB 700MiB 
	      parted /dev/md2 mkpart P5 ext4 700MiB 100%  
	      mkfs.ext4 /dev/md2p1
              mkfs.ext4 /dev/md2p2
              mkfs.ext4 /dev/md2p3
              mkfs.ext4 /dev/md2p4
	      mkfs.ext4 /dev/md2p5
              mkdir /mnt/part{1,2,3,4,5}
	      mount /dev/md2p1 /mnt/part1
	      mount /dev/md2p2 /mnt/part2
              mount /dev/md2p3 /mnt/part3
              mount /dev/md2p4 /mnt/part4
              mount /dev/md2p5 /mnt/part5
	SHELL

      end
  end
end

