---
- name: Start and enable firewalld service
  systemd:
      state: started
      enabled: yes
      name: firewalld.service
  tags:
    - firewalld

- name: Configuration firewalld for hosts
  firewalld:
      port: "{{item}}"
      permanent: yes
      state: enabled
  with_items:
     - 80/tcp
     - 443/tcp
     - 389/tcp
     - 636/tcp
     - 88/tcp
     - 464/tcp
     - 53/tcp
     - 88/udp
     - 464/udp
     - 53/udp
     - 123/udp
  tags:
     - firewalld
  notify: reload firewalld