---
- name: Setup fqdn hostname
  hostname: 
    name: "{{ inventory_hostname_short }}.forotus.org"
  tags: 
    - conf-hostname

- name: add host entry for /etc/hosts
  blockinfile: 
    dest: /etc/hosts
    content: 
        "192.168.11.10   ipaserver.forotus.org
         \n192.168.11.20   ipaclient.forotus.org"
    state: present
  tags: 
    - conf-hostname
