---
# tasks file for nfs-server

- name: create new share folder
  file:
    path: '{{ share_folder }}'
    state: directory
    mode: 0777

- name: create upload share
  file:
    path: '{{ share_folder }}/uploads'
    state: directory
    mode: 0777

- name: configure nfs-share folder
  template: 
    src: exports.j2
    dest: /etc/exports
  notify: 
    - start nfs service
  