---
- name: Basic configuration percona-mysql-server
  hosts: all
  become: true
  roles:
    - install-percona-server
    
- name: Configure master
  hosts: master
  roles:
    - master-mysql

- name: Configure slave
  hosts: slave
  roles: 
    - slave-mysql
