# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "otuslinux"
    config.vm.network "public_network", :mac => "080027ff13ac"
    config.vm.synced_folder ".", "/vagrant"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    config.vm.provision "shell", inline: <<-SHELL
    
    SHELL

  end

  