---
sysctl_config:

#Disable ipv6 (my company not use him)
  net.ipv6.conf.all.disable_ipv6: 1

# Increase system file descriptor limit
  fs.file-max: 100000

# Discourage Linux from swapping idle processes to disk (default 60)
  vm.swappiness: 10

# Increase ephermeral IP ports
  net.ipv4.ip_local_port_range: 10000 65000

# Increase Linux autotuning TCP buffer limits
# Set max to 16MB for 1GE and 32M (33554432) or 54M (56623104) for 10GE
# Don't set tcp_mem itself! Let the kernel scale it based on RAM.
  net.core.rmem_max: 16777216
  net.core.wmem_max: 16777216
  net.core.rmem_default: 16777216
  net.core.wmem_default: 16777216
  net.core.optmem_max: 40960
  net.ipv4.tcp_rmem: 4096 87380 16777216
  net.ipv4.tcp_wmem: 4096 65536 16777216

# Make room for more TIME_WAIT sockets due to more clients,
# and allow them to be reused if we run out of sockets
# Also increase the max packet backlog
  net.core.netdev_max_backlog: 50000
  net.ipv4.tcp_max_syn_backlog: 30000
  net.ipv4.tcp_max_tw_buckets: 2000000
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_fin_timeout: 10

# Disable TCP slow start on idle connections
  net.ipv4.tcp_slow_start_after_idle: 0

# If your servers talk UDP, also up these limits
  net.ipv4.udp_rmem_min: 8192
  net.ipv4.udp_wmem_min: 8192

# Disable source routing and redirects
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.default.send_redirects: 0
# Log packets with impossible addresses for security
#net.ipv4.conf.default.log_martians: 1
#net.ipv4.conf.all.log_martians: 1
#^^^^Recomended enable only debug system^^^

#Disable ICMP redirect
  net.ipv4.conf.all.accept_redirects: 0 
  net.ipv4.conf.default.accept_redirects: 0 
  net.ipv4.conf.all.secure_redirects: 0 
  net.ipv4.conf.default.secure_redirects: 0 

#Enable TCP Fast Open
  net.ipv4.tcp_fastopen: 3

#Change TCP keepalive parameters
  net.ipv4.tcp_keepalive_time: 120 
  net.ipv4.tcp_keepalive_intvl: 10 
  net.ipv4.tcp_keepalive_probes: 6

#Enable MTU probing
  net.ipv4.tcp_mtu_probing: 1

#TCP SYN cookie protection
  net.ipv4.tcp_syncookies: 1

#TCP SYN cookie protection
# net.ipv4.tcp_rfc1337: 1
#^^^^^I dont now need him^^

#Reverse path filtering
  net.ipv4.conf.default.rp_filter: 1 
  net.ipv4.conf.all.rp_filter: 1